### ISSUE TITLE
CrDroid home crashes when trying to change wallpaper

### ISSUE THREAD

**Issue by nilaysriv** [crdroidandroid/android_packages_apps_Launcher3#101]
Android 11
crDRoid 7.1

Launcher crashes when changing wallpaper.
![photo_2020-12-29_14-59-17](https://user-images.githubusercontent.com/76720071/103273961-8786db80-49e6-11eb-9843-4984119c8663.jpg)

**Comment by gwolf2u** [comment]
can you please provide logcat

**Comment by gwolf2u** [comment]
fixed by https://github.com/crdroidandroid/android_packages_apps_WallpaperPicker2/commit/33a88ea048e832ed72c20ebe7dca91990215afde
