### ISSUE TITLE
"Grid style recent apps" sliding visual bug

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_packages_apps_Launcher3#242]
Hi.

It's hard for me to explain this in English, so here is a video with demonstration of this problem

https://user-images.githubusercontent.com/31875619/173353306-3e765bde-b731-4373-86f4-986b06381f2f.mp4

**Comment by gwolf2u** [comment]
what's your screen size?

**Comment by ghost** [comment]
> what's your screen size?

adb output:
```
surya:/ $ wm size
Physical size: 1080x2400
surya:/ $ wm density
Physical density: 440
Override density: 396
```

Device spec
https://github.com/crdroidandroid/android_device_xiaomi_surya

Upd.

Maybe this is important information
Changing the Settings => "Display" => "Display size" does not affect anything

Upd. 2

Using default density value, without overriding it also has no effect (same after reboot)

**Comment by gwolf2u** [comment]
still present in 8.7?

**Comment by ghost** [comment]
Yes

https://user-images.githubusercontent.com/31875619/179369641-f672936b-4d39-443c-9429-cb2bc2d565c9.mp4
