### ISSUE TITLE
Dock icons not changing in 4x5 grid 

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_packages_apps_Launcher3#244]
Dock icon number not changing in 4x5 grid but its changing when using 5x5, 3x3, 2x2 etc 
Display size 6.67inch , device miatoll 
Cr droid 8.5 , build date - Sat Jun 11 12:12:57 +0430 2022

![Screenshot_20220619-090439_crDroid Home](https://user-images.githubusercontent.com/104545685/174464713-a72cac60-495c-44ca-b84a-98de4292740c.png)
![Screenshot_20220619-090500_crDroid Home](https://user-images.githubusercontent.com/104545685/174464715-d59d6bb9-b99a-4482-96b9-27f6b22bd983.png)

2. Themed icons not applying in apps(which supports themed icons) when using icon pack 
![Screenshot_20220619-090604_crDroid Home](https://user-images.githubusercontent.com/104545685/174464777-d83d1296-7834-440f-832a-3bc235834cce.png)
![Screenshot_20220619-090615_crDroid Home](https://user-images.githubusercontent.com/104545685/174464778-50b17c6f-84e7-4e78-93b4-eab8da3adf8d.png)

**Comment by neobuddy89** [comment]
dock icons are not dependent on grid size.

**Comment by gwolf2u** [comment]
fixed by https://github.com/crdroidandroid/android_packages_apps_Launcher3/commit/af4958f5f369d2bc00c53e8b90519e1f989861a9 ?

**Comment by neobuddy89** [comment]
Yes.
