### ISSUE TITLE
"Screenshot" and "Clear all" text color bug in recents.

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_packages_apps_Launcher3#264]
Hi

With different background opacity sometimes color of this elements is wrong.
![Screenshot_20220804-214921_crDroid Home](https://user-images.githubusercontent.com/31875619/182931103-c3753c54-b9e5-45cd-bb0d-e1f2a5070548.png)
![Screenshot_20220804-215050_crDroid Home](https://user-images.githubusercontent.com/31875619/182931116-3a577a4a-b03a-4998-94d8-2cb3f203c6de.png)

While statusbar elements color is correct

**Comment by gwolf2u** [comment]
still happening on latest 8.8?

**Comment by ghost** [comment]
Yes.
