### ISSUE TITLE
crDroid Launcher crashes if on home screen isn't available space for widgets

### ISSUE THREAD

**Issue by iogh07** [crdroidandroid/android_packages_apps_Launcher3#324]
> time: 1676210354585
> msg: java.lang.IllegalArgumentException: width & height must be > 0
> stacktrace: java.lang.IllegalArgumentException: width & height must be > 0
> 	at android.graphics.Bitmap.createBitmap(Bitmap.java:1289)
> 	at android.graphics.Bitmap.createBitmap(Bitmap.java:1266)
> 	at com.android.launcher3.icons.BitmapRenderer.createHardwareBitmap(BitmapRenderer.java:52)
> 	at com.android.launcher3.Workspace.createWidgetDrawable(Workspace.java:2873)
> 	at com.android.launcher3.Workspace.animateWidgetDrop(Workspace.java:2955)
> 	at com.android.launcher3.Workspace.onDropExternal(Workspace.java:2781)
> 	at com.android.launcher3.Workspace.onDrop(Workspace.java:1953)
> 	at com.android.launcher3.dragndrop.DragController.drop(DragController.java:543)
> 	at com.android.launcher3.dragndrop.DragController.onDriverDragEnd(DragController.java:375)
> 	at com.android.launcher3.dragndrop.DragDriver$InternalDragDriver.onTouchEvent(DragDriver.java:188)
> 	at com.android.launcher3.dragndrop.DragController.onControllerTouchEvent(DragController.java:429)
> 	at com.android.launcher3.views.BaseDragLayer.onTouchEvent(BaseDragLayer.java:267)
> 	at android.view.View.dispatchTouchEvent(View.java:15010)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3115)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
> 	at com.android.launcher3.views.BaseDragLayer.dispatchTouchEvent(BaseDragLayer.java:302)
> 	at com.android.launcher3.dragndrop.DragLayer.dispatchTouchEvent(DragLayer.java:219)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
> 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
> 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1906)
> 	at android.app.Activity.dispatchTouchEvent(Activity.java:4263)
> 	at com.android.launcher3.Launcher.dispatchTouchEvent(Launcher.java:2054)
> 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
> 	at android.view.View.dispatchPointerEvent(View.java:15269)
> 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6659)
> 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6459)
> 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5910)
> 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5967)
> 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5933)
> 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6098)
> 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5941)
> 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6155)
> 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5914)
> 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5967)
> 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5933)
> 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5941)
> 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5914)
> 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9001)
> 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8952)
> 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8921)
> 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9124)
> 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
> 	at android.os.MessageQueue.nativePollOnce(Native Method)
> 	at android.os.MessageQueue.next(MessageQueue.java:335)
> 	at android.os.Looper.loopOnce(Looper.java:161)
> 	at android.os.Looper.loop(Looper.java:288)
> 	at android.app.ActivityThread.main(ActivityThread.java:7872)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)

	
	Place a widget bigger than available space left on the homescreen, will get the launcher crashing
	EX: I placed Google Calendar month view widget on the homescreen with only At a glance widget on the homescreen, crash
	If I'm placing the widget on a new homescreen, no crashing

**Comment by gwolf2u** [comment]
https://github.com/crdroidandroid/issue_tracker/issues/new/choose
