### ISSUE TITLE
Lost CRDROID original launcher

### ISSUE THREAD

**Issue by yoyoda2048** [crdroidandroid/android_packages_apps_Launcher3#332]
Hello
I just installed CRDROID 9.2 + Nik Gapps Full on my REDMI NOTE 8 Ginkgo everything is ok. However I don't have the CRDROID launcher, it has been replaced by the basic PIXEL launcher from Google, so I can't remove At a Glance and customize my home screen. Is there any way to get the original launcher back?
Sorry I don't know if this is the good place to post and for my english.
Regards

**Comment by neobuddy89** [comment]
Use MindTheGapps or NikGapps Core

**Comment by yoyoda2048** [comment]
I started with the NikGapp core pack but with this one I don't have access to the location functions so no GPS so I can't use Google Maps or other such applications. With the full pack everything is ok.

**Comment by yoyoda2048** [comment]
I started from scratch with the core pack and it works.
Thanks
