### ISSUE TITLE
Toggle to automatically reload on dark mode

### ISSUE THREAD

**Issue by stellessia** [crdroidandroid/android_packages_apps_Launcher3#387]
# The issue
Hello, I'm having an issue related to icon packs. They don't re-apply if dark mode gets enabled/disabled, here's my screen record:

https://github.com/crdroidandroid/android_packages_apps_Launcher3/assets/81514356/5c801154-7b9f-46c7-aef2-460e29d486f3

# My suggestion
Add toggle to automatically reload icon pack when dark mode gets altered, that's all.

**Comment by gwolf2u** [comment]
use issue tracker
