### ISSUE TITLE
Add an option to hide icon text

### ISSUE THREAD

**Issue by loupianche** [crdroidandroid/android_packages_apps_Launcher3#46]
I really miss a feature from LineageOS: hidding icon text in launcher.

And if you add this, just do this better than LineageOS: hide text for app groups too.

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_packages_apps_Launcher3/commit/4b6785bc6496d58711d8107324171e3808ad0d6d
https://github.com/crdroidandroid/android_packages_apps_Launcher3/commit/5743990f03f5402397346a0968b476563b1c3bfe
